---

- hosts: etcd
  become: yes
  become_method: sudo
  roles:
    - etcd
    - flannel-config
    - flannel

- hosts: master
  become: yes
  become_method: sudo
  roles:
    - flannel
    - master
    - skydns
    - kube-dashboard

- hosts: minions
  become: yes
  become_method: sudo
  roles:
    - flannel
    - minion


---
- hosts: gluster
  roles:
    - gluster-server
    - gluster-client

- hosts: all 
  roles:
    - gluster-client
