---
- name: Download etcd pkgs
  get_url: url={{ fileserver_url }}/etcd-2.2.5-5.ael7b.ppc64le.rpm dest=/tmp

- name: Install etcd pkgs
  yum: name=/tmp/etcd-2.2.5-5.ael7b.ppc64le.rpm

- name: Write etcd config file
  copy: src=etcd.conf dest=/etc/etcd/etcd.conf
  notify:
        - restart etcd

- name: Enable etcd
  service: name=etcd enabled=yes

- name: Start etcd
  service: name=etcd state=started
  register: started_etcd

