---
- name: Download flannel
  get_url: url={{ fileserver_url }}/flannel-0.5.5-5.rpm dest=/tmp

- name: Install flannel
  yum: name=/tmp/flannel-0.5.5-5.rpm 

- name: Install Flannel config file
  template: src=flanneld.j2 dest=/etc/sysconfig/flanneld
  notify:
          - restart flannel

- name: write the docker.service.d/flannel.conf file for docker
  template: src=flannel.conf.j2 dest=/usr/lib/systemd/system/docker.service.d/flannel.conf

- name: Launch Flannel
  service: name=flanneld state=started enabled=yes
  notify:
          - stop docker
          - delete docker0
          - start docker
          - restart kubelet
